name: ssg
description: Custom Static Site Generator for TechnicJelle's Website
version: 0.0.1
repository: https://github.com/TechnicJelle/TechnicJelle

environment:
  sdk: ^3.9.2

dependencies:
  checked_yaml: ^2.0.4
  path: ^1.9.0

dev_dependencies:
  very_good_analysis: ^10.0.0
