name: ssg
description: Custom Static Site Generator for TechnicJelle's Website
version: 0.0.1
repository: https://github.com/TechnicJelle/TechnicJelle
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  checked_yaml: ^2.0.4
  github: ^9.25.0
  logging: ^1.3.0
  path: ^1.9.1
  techs_html_bindings:
    git:
      url: https://github.com/TechnicJelle/techs_html_bindings.git
      ref: main

dev_dependencies:
  very_good_analysis: ^10.0.0
